// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed icon/migetauth.png
var resourceAppIconData []byte
var resourceAppIcon = &fyne.StaticResource{
	StaticName:    "icon/migetauth.png",
	StaticContent: resourceAppIconData,
}
